### ISSUE TITLE
Fix: GDPR / HIPAA compliance

### ISSUE THREAD

**Issue by dpaez** [geut/permanent-seeder#154]

**Comment by chartgerink** [comment]
IP addresses are considered identifiable information under GDPR.

At the moment the public page is exposed automatically after initializing the permanent seeder, and exposes the connected IP addresses of the peers for each Hyperdrive. It would be helpful if IP addresses are pseudonymized by default (e.g., with a hash + salt) so that this data doesn't leak. Maybe the hash and salt could be set in the `settings.toml`?
